### ISSUE TITLE
Docs are already reflecting the un-released >4.0 new version

### ISSUE THREAD

**Issue by mpoli** [jazzband/django-robots#114]
The [official documentation](https://django-robots.readthedocs.io/en/latest/) is already reflecting the https://github.com/jazzband/django-robots/commit/70da7606974b915d57e038f8bdf31c0b21be7e45 commit that added official support for django 3.2 LTS and 4.0, addressing the AutoField break from django 3.1.

But this commit hasn't been released into a version yet, and as such new installers are led to believe that the 4.0 release already encompasses these changes and support, which isn't true.

**Comment by tony** [comment]
@mpoli Sorry for any inconvenience caused. I'm a part time / co-lead. Taking a look!

**Comment by tony** [comment]
Prereleased [5.0b1](https://pypi.org/project/django-robots/5.0b1/).

If you are using django 3.1 or 3.2 please let me know how this works

**Comment by mpoli** [comment]
@tony works for me, setup is described in #117.

Thank you!

**Comment by mpoli** [comment]
Issue solved by the release of 5.0b1.

**Comment by tony** [comment]
@mpoli As an update, [5.0](https://pypi.org/project/django-robots/5.0/) has been published
