### ISSUE TITLE
Six is used in version 4.0 but not included in the project requirements

### ISSUE THREAD

**Issue by db654** [jazzband/django-robots#116]
```
robots/models.py", line 5, in <module>
    from six import python_2_unicode_compatible, u
ModuleNotFoundError: No module named 'six'
```

**Comment by tony** [comment]
@db654 Hi there, sorry for any inconvenience caused!

I'm a part time / co-lead and taking a closer look into this.

**Comment by tony** [comment]
This will be overcome by the next version release. No more `six` in that.

If need back I can create a branch to backport to the old version - but let's see how the next one goes

**Comment by tony** [comment]
@db654 [5.0b1](https://pypi.org/project/django-robots/5.0b1/) is prereleased if you'd like to try it.  No `six` dependency.  Let me know if that works

**Comment by tony** [comment]
[5.0](https://pypi.org/project/django-robots/5.0/) is now live

I am going to close this for now as it's been overcome in the most recent release, if the issue persists please make a new issue and cite this one.
