### ISSUE TITLE
Release 4.0.1 with support to Django 3.2

### ISSUE THREAD

**Issue by mpoli** [jazzband/django-robots#117]
Support for Django 3.2 is already in HEAD (https://github.com/jazzband/django-robots/commit/70da7606974b915d57e038f8bdf31c0b21be7e45) for almost 2 months now.

The presented documentation already reflects this commit, but the available [PyPi package](https://pypi.org/project/django-robots/) does not include these updates in HEAD (https://github.com/jazzband/django-robots/issues/114).

Packing a release that adds support to Django 3.2 and fixes this documentation mismatching would be very welcomed and would rid many of us of ugly git-commit-pinning in requirements.txt.

**Comment by tony** [comment]
@mpoli Prereleased [5.0b1](https://pypi.org/project/django-robots/5.0b1/).  Can we have a few testers? Would like to make sure this is safe before publishing final release.

**Comment by tony** [comment]
@mpoli If we need a django 3.2-only release for 4.0.1 let me know, 4.0 support in #112 was already in at the time of this issue

Would like some tests for 5.0b1 for anyone using 3.0, 3.1, 3.2 to make sure this works for them

**Comment by mpoli** [comment]
Thank you @tony for the release and work on this package.

I can confirm that 5.0b1 is working for me. I have the following setup:

* python 3.10.0
* django 3.2.11

**Comment by tony** [comment]
You're very welcome!  :) Posting here also that [5.0](https://pypi.org/project/django-robots/5.0/) has been published
