### ISSUE TITLE
Django 4 is not supported 

### ISSUE THREAD

**Issue by Nour833** [jazzband/django-robots#118]
The error code is :
      File "/home/***/***/venv/lib/python3.9/site-packages/robots/models.py", line 4, in <module>
          from django.utils.translation import ugettext_lazy as _
      ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation' (/home/nour/LPM/venv/lib/python3.9/site-packages/django/utils/

We must change ugettextlazy to gettextlazy  in import section to solve the problem
And THX <3 .

**Comment by tony** [comment]
@Nour833 [5.0b1](https://pypi.org/project/django-robots/5.0b1/) is available on PyPI if you'd like to try. Feedback is welcome, want to be sure this doesn't raise any issues on systems we didn't catch in CI

**Comment by Nour833** [comment]
Great working very well no single issue!
Thank you

**Comment by tony** [comment]
@Nour833 thank you!  If I may ask, what django and python versions?

After I get one more confirmation it's working I will push the final release

**Comment by Nour833** [comment]
django 4.0.1  and I used both python 3.9.7 
I will try now python 3.10 pls wait

**Comment by Nour833** [comment]
Django 4.0.1 and Python 3.10.0
working fine 
you are welcome

**Comment by tony** [comment]
@Nour833 Thank you for testing on both of these.  I will notify here will I post the final release

**Comment by tony** [comment]
[5.0](https://pypi.org/project/django-robots/5.0/) has been published

For now I will close this issue, if anything else crops up please free to make a new one and cite this if needed
