### ISSUE TITLE
views.RuleList.get_sitemap_urls modifies settings.SITEMAP_URLS

### ISSUE THREAD

**Issue by pilt** [jazzband/django-robots#37]
Because of this line: https://github.com/jezdez/django-robots/blob/8d59b0cb7c9d3fd0eb0bd11fbb6f847b390369e5/robots/views.py#L33.

Is get_sitemap_urls intended to have this side effect?  If not, a possible fix would be to change the line to
`sitemap_urls = settings.SITEMAP_URLS[::]`.

**Comment by jezdez** [comment]
Good catch, mind if you open a PR?

**Comment by SalahAdDin** [comment]
Pr :+1:
