### ISSUE TITLE
Tests no longer passes in older Django versions

### ISSUE THREAD

**Issue by ReekenX** [jazzband/django-robots#41]
When you have Django 1.5.\* and you run tests, django-robots 1.1 fails with message:

```
File "/lib/python2.7/site-packages/robots/forms.py", line 7, in <module>
  class RuleAdminForm(forms.ModelForm):
File "/lib/python2.7/site-packages/django/forms/models.py", line 221, in __new__
  raise FieldError(message)
FieldError: Unknown field(s) (a, l, _) specified for Rule
```

This is related to https://github.com/jezdez/django-robots/pull/30 where `__all__` was added to support Django 1.8 which causes to break in older versions.

**Comment by yakky** [comment]
I think we can only declare a list of supported Django versions for each robots version. Django 1.5 it's not supported anymore by upstream project, so I guess it does not have much sense to keep newer versions of django-robots compatible with it

**Comment by ReekenX** [comment]
You don't want to have django-robots backward compatible? It's easy to fix just with couple lines of code by checking version number.

I think such feature is gread to offer.

**Comment by yakky** [comment]
At some point supporting older Django versions becomes a burden and makes code less maintable. django-robots 1.0 is still available for projects using older Django versions, thus I don't see a major issue here

**Comment by ReekenX** [comment]
But then another issue: how to know which version to use? Install instructions says about how to install with `pip` easily. But it does not say anything about that it will be broken once you try to run on version 1.5 or below.

Other open source projects normally have range of versions which are supported. For example now this project is 1.8+, with easy fix it would be 1.5 - 1.8+, where, at some point, older versions can be easily dropped.

**Comment by yakky** [comment]
Documenting the Django compatibility seems the logical option here.
Version 1.1 is compatible with 1.6 and up, anyway

**Comment by yakky** [comment]
Closing this. Supported versions are already documented in reame
