### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by tspecht** [jazzband/django-robots#46]
Hi guys,

is python 3 supported? If yes, maybe would be nice to add it to setup.py so that others would know and script could detect that :)

**Comment by jezdez** [comment]
It's not at the moment, it would be advertised as such if.

**Comment by tspecht** [comment]
Are there any plans on supporting it?

**Comment by jezdez** [comment]
@tspecht Even better, the app is part of [Jazzband](https://jazzband.co) now, and you can become a member and work on it yourself! [More info](https://jazzband.co/news/2015/12/17/launching-jazzband) if you're interested.

**Comment by SalahAdDin** [comment]
I'm working django-robots in python3.5 without problem.

**Comment by tspecht** [comment]
I'd be happy to do that! In fact I just joined the organization, pulled the code and ran modernize. Apparently no changes are needed? Since there are no tests present I'm struggling to verify it in a CI-compatible way... would it then be enough to simply add the compatibility to the setup.py file?

**Comment by jezdez** [comment]
@tspecht It would be preferable to add CI.

**Comment by tspecht** [comment]
I know, I'd also prefer that. Any clues on how to get that started code-wise (I'm familiar with travis-ci and all the rest)

**Comment by jezdez** [comment]
@tspecht I've enabled Travis, that's a common choice for Django projects
