### ISSUE TITLE
Sitemap URL with double scheme

### ISSUE THREAD

**Issue by lmanzurv** [jazzband/django-robots#62]
I have a setup of Django CMS + Gunicorn + Nginx and when the robots.txt file is displayed, it shows the scheme of the URL twice.

This is the robots file that is generated:

User-agent: *
Allow: /
Disallow: /admin

Host: https://www.chitwa.co.za
**Sitemap: https://https://www.chitwa.co.za/en/sitemap.xml**

**Comment by tyapkov** [comment]
I have the same issue. If I am changing the site from https://mysite.com to mysite.com then everything works, but now the host in robots.txt is not correct

**Comment by yakky** [comment]
@lmanzurv @tyapkov could you test the linked PR?

**Comment by tyapkov** [comment]
@yakky the code looks for me okay and it should fix the problem, but I don't have local repo so can test it only when it will be merged and I will update django-robots on my server.

**Comment by yakky** [comment]
@tyapkov you can just ``pip install https://github.com/yakky/django-robots/archive/issue-64/fix_double_scheme.zip`` do install the PR code

**Comment by tyapkov** [comment]
@yakky true. Thanks for the hint! i have installed it on development server with:

pip install https://github.com/yakky/django-robots/archive/issue-64/fix_double_scheme.zip --upgrade

After changing site to: http://127.0.0.1:8007

My robots.txt looks like:

User-agent: *
Disallow:

Host: http://127.0.0.1:8007
Sitemap: http://127.0.0.1:8007/sitemap.xml

But sitemap still with double http:

<urlset><url><loc>http://http://127.0.0.1:8007/schools/6/about/</loc><changefreq>weekly</changefreq><priority>0.6</priority></url>
....

**Comment by tyapkov** [comment]
@yakky Wait, but django-robots not responsible for generating sitemap.xml? right? if so then I cannot specify my site in admin with http or https, because it doubles in sitemap. If so then the feature will be never used.

**Comment by lmanzurv** [comment]
@tyapkov My solution was to not include the protocol in the Site domain so it wouldn't be repeated

**Comment by tyapkov** [comment]
@lmanzurv yes, in your case just (if you have http website) just not including protocol into the site will work fine.

**Comment by lmanzurv** [comment]
@tyapkov All my sites are https and they work (redirection from http to https done through nginx)

**Comment by tyapkov** [comment]
@lmanzurv did you apply the bug fix mentioned by @yakky or you just working on previous version or django-robots? what is your host in robots.txt if you dont use protocol in site?

**Comment by tyapkov** [comment]
@yakky  i was wrong yesterday. We shouldn't use protocol in Site. If to change site to 127.0.0.1:8007 then my robots.txt look like:

```
User-agent: *
Disallow:

Host: http://127.0.0.1:8007
Sitemap: http://127.0.0.1:8007/sitemap.xml
```

Now http is always included (what will probably work for crawlers) but according to logic if site is specified and ROBOTS_SITE_BY_REQUEST = False then it should be just 127.0.0.1:8007, right?

**Comment by lmanzurv** [comment]
@tyapkov With the fix applied, using ROBOTS_USE_SCHEME_IN_HOST = True and without adding the host in the Site domain name, it all works fine

**Comment by tyapkov** [comment]
@Imanzurv thanks, yes, the bug is solved. I am only thinking if protocol is always required in robots.txt? Right now it looks like it is always included.

**Comment by lmanzurv** [comment]
@tyapkov In the sitemap it is, in the host, it can be disabled. The sitemap URL is being created through the standard Sitemap definition from Django (or Django CMS in my case)

**Comment by tyapkov** [comment]
@lmanzurv How did you disable it?

**Comment by tyapkov** [comment]
@lmanzurv true, my package django-robots didn't fully updated that is why I had problems.
Now see the same, protocol can be disabled in Host record, but for sitemap is always shown.

**Comment by yakky** [comment]
@tyapkov sitemap and hosts are very different things, actually. Sitemap is the full URL to an object (the sitemap :) ) and thus it requires full protocol declaration. Host is a generic directive with much less clear definition, and different engines inteprets it differently. It can be regarded as both a domain or a URL
It makes sense to keep it configurable, I guess
