### ISSUE TITLE
Swappable site model

### ISSUE THREAD

**Issue by mikedingjan** [jazzband/django-robots#64]
Hi,

As stated in issue #63 adding support for wagtail isn't in scope of this package, I agree on that.. I was wondering if it's feasible to have the site model via a setting (just like django's swappable User model). That way we can easily integrate with whatever package which uses a different model for its Sites.

Hope you'll agree on this? If so, we can provide a PR for this..

**Comment by jezdez** [comment]
Yeah, but the swappable models can be brittle when it comes to database migrations. So any patch to add such a feature would need to be very careful about backward compatibility for existing projects using the current version of django-robots without that feature. So elaborate docs and tests are required.

**Comment by mikedingjan** [comment]
Hey @Adrian-Turjak , 
Thanks for sharing, will definitely check it out!
