### ISSUE TITLE
Django 2.0 support

### ISSUE THREAD

**Issue by tony** [jazzband/django-robots#81]
https://github.com/develtech/django-robots/tree/django-2.0

- [x] Update tox 8f5b5f61
- [x] Update travis 8f5b5f61
- [x] #82 Drop 1.10 and below? 86cf942
- [x] b85ae48 #79 urlresolvers update
- [x] Test fix: d6acbfd

   ```
     File "/Users/me/work/python/django-robots/tests/test_utils/urls.py", line 16, in <module>
       url(r'^jsi18n/(?P<packages>\S+?)/$', django.views.i18n.javascript_catalog),  # NOQA
   AttributeError: module 'django.views.i18n' has no attribute 'javascript_catalog'
   ```
- [x] Test fix: 6a5baf7

   ```
     File "/Users/me/work/python/django-robots/tests/test_utils/urls.py", line 16, in <module>
    url(r'^admin/', include(admin.site.urls)),  # NOQA
     File "/Users/me/work/python/django-robots/.venv/lib/python3.6/site-packages/django/urls/conf.py", line 27, in include
       'provide the namespace argument to include() instead.' % len(arg)
    django.core.exceptions.ImproperlyConfigured: Passing a 3-tuple to include() is not supported. Pass a 2-tuple containing the list of patterns and app_name, and provide the namespace argument to include() instead.
   ```

- [x] ab18b86 Inside tests: Using User.is_authenticated() and User.is_anonymous() as methods rather than properties is no longer supported. [source](https://docs.djangoproject.com/en/2.0/releases/2.0/):

   ```
   ERROR: test_view_site_2 (tests.test_views.ViewTest)
   Traceback (most recent call last):
     File "/Users/me/work/python/django-robots/tests/test_views.py", line 82, in test_view_site_2
       request = self.get_request(path='/', user=AnonymousUser(), lang='en')
     File "/Users/me/work/python/django-robots/tests/base.py", line 31, in get_request
       if user.is_authenticated():
   TypeError: 'bool' object is not callable
   ```

   It should be valid to use it as a property in Django 1.10+ [source](https://docs.djangoproject.com/en/1.11/ref/contrib/auth/#django.contrib.auth.models.User.is_authenticated)

**Comment by mpasternak** [comment]
Wowwww, looks like I duplicated all the efforts. https://github.com/jazzband/django-robots/pull/85 Maintainers, how about some merge and/or release?

**Comment by idlesign** [comment]
@tony Please push 3.1 to PyPI.

**Comment by tony** [comment]
I don't have PyPI access.
