### ISSUE TITLE
Update pypi with 3.1.0

### ISSUE THREAD

**Issue by gfhuseyinyilmaz** [jazzband/django-robots#87]
Hey,
It seems like pypi still has  3.0
https://pypi.python.org/pypi/django-robots

Can you guys also update pypi with 3.1.0 so it would be downlodable with pip?

**Comment by gfhuseyinyilmaz** [comment]
For people who do not want to wait you can add tag 3.1.0 directly from github to your requirements.
Just add following line to your requirements.txt file.

```
# django-robots
-e git+https://github.com/jazzband/django-robots.git@3.1.0#egg=robots
```

**Comment by SalahAdDin** [comment]
@jazzband-bot @gfhuseyinyilmaz what's about this?

**Comment by jezdez** [comment]
Sorry for the delay, I'll need to set up the new [project releases](https://jazzband.co/about/releases) as recently introduced. Stay tuned.

**Comment by Jastrzebowski** [comment]
@jezdez any plans for it?

**Comment by ratson** [comment]
@tony @jezdez @jazzband-bot Is this still in progress?

**Comment by SalahAdDin** [comment]
@ratson, yes.

**Comment by sassanh** [comment]
Can we release this without the automatic release system?

**Comment by jezdez** [comment]
Ugh, tomorrow...

**Comment by jezdez** [comment]
Thank you for your patience folks 🙇 

I've enabled [project releases](https://jazzband.co/about/releases) and made @tony and me project lead members. That means we'll get notified when a git tag is pushed to GitHub and the deploy via Travis succeeds. Once that's done we'll confirm the release to push to PyPI.

**Comment by jezdez** [comment]
Also, a *new* 3.1.0 tag is running on Travis right now and will trigger this system. So expect a release on PyPI soon.
