### ISSUE TITLE
Django 3.0 Support

### ISSUE THREAD

**Issue by laactech** [jazzband/django-robots#94]
Thanks for this package and your work maintaining it.

- **OS version and name**: Ubuntu 18.04
- **python version**: 3.8
- **django version**: 3.0
- **django-robots version**: 3.1.0

I am attempting to upgrade my django project to python 3.8 and django 3.0, and when I attempt to run my test suite, I receive this error from `robots/models.py` on line 3.

```python
ImportError: cannot import name 'python_2_unicode_compatible' from 'django.utils.encoding'
```
I believe that Django 3.0 removes this due to the drop in Python 2 support.

https://docs.djangoproject.com/en/3.0/releases/3.0/#removed-private-python-2-compatibility-apis

To achieve Django 3.0 support, I believe this will have to be removed from django-robots.

**Comment by peboun** [comment]
ModuleNotFoundError: No module named 'django.utils.six' too
